worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    # Define log format
    log_format combined_custom '$remote_addr - $remote_user [$time_local] '
                           '"$request" $status $body_bytes_sent '
                           '"$http_referer" "$http_user_agent"';

    # Add MIME type for JavaScript files
    types {
        application/javascript  js;
        text/css               css;
    }

    server {
        listen ${PORT} default_server;
        server_name _;
        root /app/public;
        index index.php;

        # Add security headers
        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-Content-Type-Options "nosniff";

        # Handle static files
        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
            try_files $uri =404;
            expires max;
            add_header Cache-Control "public, no-transform";
            access_log off;
        }

        # Main application handling
        location / {
            try_files $uri $uri/ /index.php$is_args$args;
        }

        # PHP handling
        location ~ \.php$ {
            try_files $uri =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
            fastcgi_param HTTP_X_FORWARDED_PROTO $http_x_forwarded_proto;
            fastcgi_param HTTPS on;
        }

        # Deny access to hidden files
        location ~ /\. {
            deny all;
        }

        # Logs - using the defined format
        error_log  /dev/stderr warn;
        access_log /dev/stdout combined_custom;
    }
}
